### ISSUE TITLE
The emoji panel in mastodon allocates a gazillion images in the texture cache.

### ISSUE THREAD

**Issue by nical** [servo/webrender#2035]
Log into mastodon and click on the thing to add emojis.

This will allocate a *lot* of items (the emojis themselves) in the texture cache and a lot of textures to hold them. On my fedora+intel laptop this freezes the entire desktop for dozens of seconds.

**Comment by nical** [comment]
To give a rough idea of how epic this is, here is a screenshot of the texture cache debugging view enabled (the tiny row at the bottom):

![mastodon-tex-cache](https://user-images.githubusercontent.com/264854/32773932-0c4db996-c92b-11e7-8a73-ffa3d1d7ba10.png)

**Comment by jrmuizel** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1401672 should fix that

**Comment by glennw** [comment]
@nical The gecko change has landed now - could you check if this is still an issue?

**Comment by jrmuizel** [comment]
Make sure you turn on the image.mem.shared pref

**Comment by nical** [comment]
Unfortunately this issue remains pretty much the same (on the latest nightly with the shared images pref).

Another fun thing to try (that doesn't require any account) is to type things in the awesome bar and watch the little search icon fill up the drop-down menu's texture cache as you type.

**Comment by glennw** [comment]
OK, I can see if I can repro tomorrow. It'd be interesting to log out the image keys that are being referenced in the display and see if indeed they are being shared correctly.

**Comment by nical** [comment]
The problem seems to be mostly on the gecko side, and Andrew is working on it.

**Comment by jrmuizel** [comment]
mastadon is using svg images and we don't handle them properly yet.

**Comment by glennw** [comment]
Is there anything WR-side to do here or should we close this?

**Comment by jrmuizel** [comment]
We can close it.
